kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-nbg1-01
  annotations:
    # fake it by indicating this is provisioned dynamically, so the system
    # works properly
    pv.kubernetes.io/provisioned-by: de.apricote.hcloud.csi.volumes
spec:
  storageClassName: hcloud-volumes
  # by default, the volume will be not deleted if you delete the PVC, change to
  # "Delete" if you wish the volume to be deleted automatically with the PVC
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: de.apricote.hcloud.csi.volumes
    fsType: ext4
    volumeHandle: 1952d58a-c714-11e8-bc0c-0a58ac14421e
    volumeAttributes:
      de.apricote.hcloud.csi/noformat: "true"
